export const actasData = [
  {
    id: '0',
    actaDate: 'No encontrada',
    reunionTitle: 'Reunión no encontrada',
    resumenText: 'El acta que estás buscando no ha sido encontrada.',
    documentos: [],
  },
  {
    id: '1',
    actaDate: '19/10/2023',
    reunionTitle: 'Reunión sobre la feria del software',
    resumenText: 'En la reunión sobre la feria del software, se discutió la estrategia de participación de la empresa en el evento. Se acordó asignar un presupuesto específico para la feria y se establecieron los objetivos de marketing. Se decidió que la presentación de la empresa se centrará en las últimas innovaciones en software.',
    documentos: ['Documento_1.pdf', 'Documento_2.docx'],
  },
  {
    id: '2',
    actaDate: '20/10/2023',
    reunionTitle: 'Reunión de planificación del proyecto X',
    resumenText: 'Durante la reunión de planificación del proyecto X, se revisaron los hitos y las fechas límite del proyecto. Se identificaron los recursos necesarios y se asignaron responsabilidades a los miembros del equipo. Se discutió el presupuesto y se acordaron los informes de progreso regulares.',
    documentos: ['Documento_3.pdf', 'Documento_4.docx', 'Documento_5.jpg'],
  },
  {
    id: '3',
    actaDate: '21/10/2023',
    reunionTitle: 'Reunión de revisión de presupuesto',
    resumenText: 'La reunión de revisión de presupuesto se centró en la planificación financiera del próximo trimestre. Se analizaron los gastos proyectados y se identificaron áreas donde se pueden realizar ajustes. Se acordaron las prioridades financieras y se asignaron fondos para proyectos específicos.',
    documentos: ['Documento_6.xls'],
  },
  {
    id: '4',
    actaDate: '22/10/2023',
    reunionTitle: 'Reunión de lanzamiento del producto Y',
    resumenText: 'El lanzamiento del producto Y se llevó a cabo con éxito. Se presentaron las características clave del producto a los miembros del equipo y se discutieron las estrategias de marketing y ventas para maximizar la adopción del producto en el mercado.',
    documentos: ['Documento_7.pdf', 'Documento_8.jpg'],
  },
  {
    id: '5',
    actaDate: '23/10/2023',
    reunionTitle: 'Reunión de retroalimentación de clientes',
    resumenText: 'Se recopiló retroalimentación de los clientes sobre los productos y servicios de la empresa. Se destacaron los comentarios positivos y las áreas de mejora. Se acordaron acciones específicas para abordar las inquietudes de los clientes y mejorar la satisfacción del cliente.',
    documentos: ['Documento_9.docx', 'Documento_10.pdf', 'Documento_11.jpg'],
  },
  {
    id: '6',
    actaDate: '24/10/2023',
    reunionTitle: 'Reunión de equipo de desarrollo',
    resumenText: 'Se revisó el progreso del desarrollo del software y se discutieron los desafíos técnicos. Se acordaron medidas para acelerar el desarrollo y se planificaron pruebas adicionales antes del lanzamiento. Se estableció una fecha objetivo para la finalización del proyecto.',
    documentos: ['Documento_12.pdf', 'Documento_13.docx'],
  },
  {
    id: '7',
    actaDate: '25/10/2023',
    reunionTitle: 'Reunión de ventas y marketing',
    resumenText: 'Se presentaron las estrategias de ventas y marketing para el próximo trimestre, incluyendo campañas publicitarias, promociones y eventos de ventas. Se discutió la segmentación de mercado y las metas de ventas. Se acordaron tácticas específicas para aumentar la presencia de la empresa en línea y fuera de línea.',
    documentos: ['Documento_14.pdf', 'Documento_15.jpg'],
  },
  {
    id: '8',
    actaDate: '26/10/2023',
    reunionTitle: 'Reunión de innovación de productos',
    resumenText: 'La reunión de innovación de productos se centró en la generación de ideas para nuevos productos y mejoras a los productos existentes. Se realizaron lluvias de ideas y se evaluaron las ideas presentadas. Se priorizaron las iniciativas de desarrollo de productos para el próximo año.',
    documentos: ['Documento_16.pdf', 'Documento_17.docx'],
  },
  {
    id: '9',
    actaDate: '27/10/2023',
    reunionTitle: 'Reunión de evaluación de proyectos',
    resumenText: 'Se realizó una evaluación exhaustiva de los proyectos en curso. Se revisaron los hitos, los plazos y el desempeño del equipo en cada proyecto. Se tomaron decisiones sobre la continuación, la reasignación de recursos y la finalización de proyectos.',
    documentos: ['Documento_18.pdf', 'Documento_19.xls', 'Documento_20.jpg'],
  }
];
