export const actasData = [
  /*{
    id: '0',
    actaDate: 'No encontrada',
    reunionTitle: 'Reunión no encontrada',
    resumenText: 'El acta que estás buscando no ha sido encontrada.',
    documentos: [],
  },*/
  {
    id: '1',
    actaDate: '19/10/2023',
    reunionTitle: 'Reunión sobre la feria del software',
    resumenText: 'En la reunión sobre la feria del software, se discutió la estrategia de participación de la empresa en el evento. Se acordó asignar un presupuesto específico para la feria y se establecieron los objetivos de marketing. Se decidió que la presentación de la empresa se centrará en las últimas innovaciones en software.',
    documentos: ['Documento_1.pdf', 'Documento_2.docx'],
  },
  {
    id: '2',
    actaDate: '20/10/2023',
    reunionTitle: 'Reunión de planificación del proyecto X',
    resumenText: 'La reunión abordó la planificación detallada del Proyecto X, destacando las fases críticas del desarrollo y las asignaciones de tareas. Se discutió la necesidad de una nueva herramienta de seguimiento de proyectos y se eligió por mayoría después de evaluar varias opciones. Se revisaron los protocolos de comunicación interna para mejorar la eficiencia y se acordaron fechas para las próximas revisiones de estado del proyecto.',
    documentos: ['Plan_Proyecto_X.pdf', 'Comparativa_Herramientas_Proyecto.docx', 'Protocolos_Comunicacion.pptx'],
  },
  {
    id: '3',
    actaDate: '21/10/2023',
    reunionTitle: 'Reunión de revisión de presupuesto',
    resumenText: 'En esta sesión, se realizó un análisis pormenorizado del presupuesto del último trimestre. Se identificaron posibles ahorros y se propusieron realineaciones presupuestarias para apoyar iniciativas estratégicas. La financiación adicional para la investigación y el desarrollo fue aprobada tras una discusión animada, subrayando la importancia de la innovación para el crecimiento a largo plazo de la empresa.',
    documentos: ['Informe_Presupuestario.pdf', 'Propuestas_Reasignacion.xlsx', 'Aprobacion_Inversiones.docx'],
  },
  {
    id: '4',
    actaDate: '22/10/2023',
    reunionTitle: 'Reunión de lanzamiento del producto Y',
    resumenText: 'La sesión se centró en el lanzamiento inminente del Producto Y. El equipo de marketing presentó la campaña publicitaria, que incluye anuncios digitales y tradicionales, así como esfuerzos de relaciones públicas. Se revisaron los materiales promocionales y se finalizaron los preparativos para el evento de lanzamiento. Se establecieron métricas clave de rendimiento para evaluar el éxito del lanzamiento.',
    documentos: ['Campaña_Producto_Y.pptx', 'Medios_Publicitarios.docx', 'Lista_Verificacion.pdf'],
  },
  {
    id: '5',
    actaDate: '23/10/2023',
    reunionTitle: 'Reunión de retroalimentación de clientes',
    resumenText: 'Se recopiló retroalimentación de los clientes sobre los productos y servicios de la empresa durante el último trimestre. Se destacaron comentarios sobre la facilidad de uso de la plataforma en línea, la eficiencia del soporte técnico, y se identificaron oportunidades de mejora en las opciones de personalización de productos. Los equipos de desarrollo y marketing tomaron nota de las sugerencias para la implementación de mejoras futuras. Se establecieron grupos de trabajo para revisar los flujos de trabajo y la interfaz de usuario para mejorar la experiencia general del cliente.',
    documentos: ['Retroalimentacion_Clientes.pdf', 'Resumen_Ejecutivo.pptx', 'Plan_Mejoras.xlsx', 'Transcripcion_Entrevistas.docx'],
  },
  {
    id: '6',
    actaDate: '24/10/2023',
    reunionTitle: 'Reunión de equipo de desarrollo',
    resumenText: 'El equipo de desarrollo se reunió para revisar el progreso actual del software en desarrollo, discutiendo los desafíos técnicos encontrados en la última iteración. Se acordaron estrategias para mejorar el rendimiento y la seguridad, y se designaron líderes de equipo para las tareas críticas de desarrollo. Se estableció un cronograma detallado para las próximas fases de pruebas, incluyendo pruebas unitarias, integración y aceptación por parte del usuario. También se determinaron los criterios de éxito para la próxima revisión de código y se programaron sesiones de pair programming para optimizar el flujo de trabajo.',
    documentos: ['Reporte_Progreso.pdf', 'Cronograma_Proyecto.mpp', 'Pruebas_Aceptacion.docx'],
  },
  {
    id: '7',
    actaDate: '25/10/2023',
    reunionTitle: 'Reunión de ventas y marketing',
    resumenText: 'Los equipos de ventas y marketing presentaron un análisis exhaustivo del rendimiento de las últimas campañas. Se debatieron tácticas para incrementar la generación de leads y la conversión de ventas, incluyendo la optimización de la estrategia SEO y la implementación de una nueva serie de webinars educativos. Se analizaron las métricas de las redes sociales para ajustar los esfuerzos publicitarios y se planificaron colaboraciones con influencers clave en la industria. Se finalizó con la asignación de presupuestos para las próximas campañas y se definieron las metas de ventas para el próximo trimestre.',
    documentos: ['Analisis_Marketing.pdf', 'Estrategia_Red_Social.pptx', 'Presupuesto_Publicidad.xlsx', 'Informe_Conversiones.csv'],
  },
  {
    id: '8',
    actaDate: '26/10/2023',
    reunionTitle: 'Reunión de innovación de productos',
    resumenText: 'La reunión de innovación de productos se centró en la generación de ideas para nuevos productos y mejoras a los productos existentes. Se realizaron lluvias de ideas y se evaluaron las ideas presentadas. Se priorizaron las iniciativas de desarrollo de productos para el próximo año.',
    documentos: ['Documento_16.pdf', 'Documento_17.docx'],
  },
  {
    id: '9',
    actaDate: '27/10/2023',
    reunionTitle: 'Reunión de evaluación de proyectos',
    resumenText: 'Se realizó una evaluación exhaustiva de los proyectos en curso. Se revisaron los hitos, los plazos y el desempeño del equipo en cada proyecto. Se tomaron decisiones sobre la continuación, la reasignación de recursos y la finalización de proyectos.',
    documentos: ['Documento_18.pdf', 'Documento_19.xls', 'Documento_20.jpg'],
  },
  {
    id: '10',
    actaDate: '28/10/2023',
    reunionTitle: 'Reunión de estrategia de expansión',
    resumenText: 'El comité directivo discutió los planes de expansión a nuevos mercados, centrándose en la viabilidad y los desafíos potenciales. Se exploraron las oportunidades de asociación estratégica y se establecieron grupos de trabajo para investigar las regulaciones de mercado en diferentes regiones. Se aprobó un presupuesto inicial para estudios de mercado y análisis de competencia.',
    documentos: ['Plan_Expansión.pdf', 'Estudio_Mercado_Inicial.pptx', 'Análisis_Competencia.xlsx'],
  },
  {
    id: '11',
    actaDate: '29/10/2023',
    reunionTitle: 'Reunión de actualización tecnológica',
    resumenText: 'Los líderes de TI presentaron las últimas tendencias tecnológicas y su impacto en las operaciones actuales. Se debatió la adopción de la nube y la inteligencia artificial para mejorar los procesos internos. Se aprobó un plan de migración a la nube y se formó un equipo de proyecto para supervisar la transición. También se discutieron políticas de seguridad actualizadas para salvaguardar los datos durante y después de la migración.',
    documentos: ['Presentación_Tendencias.pptx', 'Plan_Migración.docx', 'Políticas_Seguridad.pdf'],
  },
  {
    id: '12',
    actaDate: '30/10/2023',
    reunionTitle: 'Reunión de sostenibilidad y RSE',
    resumenText: 'El enfoque estuvo en las iniciativas de sostenibilidad y responsabilidad social empresarial (RSE). Se revisaron las prácticas actuales y se propusieron nuevas estrategias para mejorar la huella ecológica de la empresa. Se establecieron objetivos de sostenibilidad a corto y largo plazo y se aprobó un proyecto para la instalación de paneles solares en la sede corporativa.',
    documentos: ['Informe_Sostenibilidad.pdf', 'Estrategia_RSE.pptx', 'Paneles_Solares.docx'],
  },
  {
    id: '13',
    actaDate: '31/10/2023',
    reunionTitle: 'Reunión de seguimiento de proyectos',
    resumenText: 'La reunión se centró en el seguimiento de los proyectos clave en curso. Los gerentes de proyecto informaron sobre el progreso, los riesgos y los próximos pasos. Se identificaron los cuellos de botella y se asignaron recursos adicionales para asegurar que los plazos críticos se cumplan. Se revisaron los KPIs de los proyectos y se ajustaron los planes de proyecto según fuera necesario.',
    documentos: ['Reporte_Seguimiento.xlsx', 'Plan_Acción_Riesgos.docx', 'Actualización_KPIs.pptx'],
  },
  {
    id: '14',
    actaDate: '01/11/2023',
    reunionTitle: 'Reunión de cultura organizacional',
    resumenText: 'Los líderes de la empresa discutieron la importancia de una cultura organizacional fuerte y cómo fomentarla. Se compartieron resultados de encuestas recientes a empleados y se establecieron comités para desarrollar programas de reconocimiento y bienestar. Se aprobó un calendario de eventos de team building y se inició la planificación de un programa de liderazgo y desarrollo.',
    documentos: ['Encuesta.pdf', 'Programas_Reconocimiento.pptx', 'Calendario_Team.docx'],
  }
];
